package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/peter/atlassian-cli/internal/version"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// docsOverview is the hand-written context that leads the generated reference.
// It captures the institutional knowledge an agent needs to use the CLI well —
// things the per-command help cannot convey.
const docsOverview = `## What this CLI does

The ` + "`atlassian`" + ` CLI works with Atlassian Cloud: Jira, Confluence, Jira
Product Discovery (JPD), Compass, and cross-product issue links.

Prefer this CLI over the Atlassian MCP when a task involves: listing JPD
(Product Discovery) projects, linking Jira issues to JPD ideas, discovering
custom fields on ideas, or any Compass operation.

## Authentication

- REST commands (` + "`jira`, `confluence`, `jpd`, `link`" + `) use an API token.
  Configure ATLASSIAN_SITE_URL, ATLASSIAN_EMAIL and ATLASSIAN_API_TOKEN in a
  ` + "`.env`" + ` file (run ` + "`atlassian config init`" + `).
- GraphQL commands (` + "`compass`, `goals`, `projects`" + `) use OAuth — run
  ` + "`atlassian auth login`" + ` once. Access tokens refresh automatically.
- Running any command without credentials prints step-by-step setup help.

## Key concepts

- A JPD idea IS a Jira issue. An idea key like ` + "`NPD-129`" + ` works with both
  the ` + "`jpd ideas`" + ` commands and the generic ` + "`jira issue`" + ` commands.
- To link a Jira delivery ticket to a JPD idea so it appears in the idea's
  Delivery panel, use link type ` + "`Polaris work item link`" + `, idea first:
  ` + "`atlassian link create <IDEA-KEY> <TICKET-KEY> --type \"Polaris work item link\"`" + `.
  A generic issue link (any other type) will NOT show in the Delivery panel.
- JPD custom fields (target dates, ratings, selects) are project-specific.
  Discover a given idea's fields and their IDs with
  ` + "`atlassian jpd ideas fields <idea-key>`" + `.
- Compass is GraphQL-only. Typed commands cover common reads and component
  create/update; ` + "`atlassian compass query`" + ` runs any GraphQL operation,
  including mutations, for everything else.

## Conventions

- Every command supports ` + "`--help`" + `. Most list/get commands support ` + "`--json`" + `
  for scripting.
- Regenerate this document after upgrading the CLI: ` + "`atlassian docs --install`" + `.
`

var docsCmd = &cobra.Command{
	Use:   "docs",
	Short: "Generate CLI documentation / install a Claude Code skill",
	Long: `Generate complete, current documentation for every command by walking the
live command tree, so the output never drifts from the actual CLI.

  atlassian docs              print a Markdown reference to stdout
  atlassian docs --skill      print it wrapped as a Claude Code SKILL.md
  atlassian docs --install    write the skill to ~/.claude/skills/atlassian-cli/

Install the skill so Claude Code discovers it and uses this CLI effectively.
Re-run --install after upgrading the CLI to keep the skill current.`,
	Run: func(cmd *cobra.Command, args []string) {
		install, _ := cmd.Flags().GetBool("install")
		asSkill, _ := cmd.Flags().GetBool("skill")
		dir, _ := cmd.Flags().GetString("dir")

		body := generateDocs(rootCmd)

		if install {
			path, err := installSkill(body, dir)
			exitOnError(err)
			fmt.Printf("Installed Claude Code skill: %s\n", path)
			fmt.Println("Claude Code will discover it automatically in new sessions.")
			return
		}
		if asSkill {
			fmt.Print(skillDocument(body))
			return
		}
		fmt.Print(body)
	},
}

// skipDocsCmd reports whether a command should be left out of the docs.
func skipDocsCmd(c *cobra.Command) bool {
	n := c.Name()
	return c.Hidden || n == "help" || n == "completion"
}

// generateDocs renders a Markdown reference for every runnable command.
func generateDocs(root *cobra.Command) string {
	var cmds []*cobra.Command
	var collect func(*cobra.Command)
	collect = func(c *cobra.Command) {
		if skipDocsCmd(c) {
			return
		}
		if c.Runnable() {
			cmds = append(cmds, c)
		}
		for _, ch := range c.Commands() {
			collect(ch)
		}
	}
	collect(root)
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].CommandPath() < cmds[j].CommandPath() })

	var b strings.Builder
	fmt.Fprintf(&b, "# atlassian CLI — reference\n\n")
	fmt.Fprintf(&b, "_Generated by `atlassian docs` from CLI v%s — %d commands._\n\n",
		version.Version, len(cmds))
	b.WriteString(docsOverview)
	b.WriteString("\n## Commands\n\n")
	for _, c := range cmds {
		writeCommand(&b, c)
	}
	return b.String()
}

// writeCommand renders one command: invocation, description and flags.
func writeCommand(b *strings.Builder, c *cobra.Command) {
	fmt.Fprintf(b, "### `%s`\n\n", c.UseLine())

	desc := strings.TrimSpace(c.Long)
	if desc == "" {
		desc = strings.TrimSpace(c.Short)
	}
	if desc != "" {
		fmt.Fprintf(b, "%s\n\n", desc)
	}

	var flags []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		line := fmt.Sprintf("- `--%s` (%s) — %s", f.Name, f.Value.Type(), f.Usage)
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "0" {
			line += fmt.Sprintf(" [default: %s]", f.DefValue)
		}
		flags = append(flags, line)
	})
	if len(flags) > 0 {
		b.WriteString("Flags:\n")
		for _, f := range flags {
			b.WriteString(f + "\n")
		}
		b.WriteString("\n")
	}
}

// skillDocument wraps the reference body with Claude Code skill frontmatter.
func skillDocument(body string) string {
	const frontmatter = `---
name: atlassian-cli
description: >-
  Reference for the 'atlassian' command-line tool — work with Jira issues,
  Confluence pages, Jira Product Discovery (JPD) ideas, Compass components,
  and cross-product issue links. Use this skill whenever a task involves
  Atlassian, Jira, Confluence, JPD, or Compass and the 'atlassian' command
  is available on PATH.
---

`
	return frontmatter + body
}

// installSkill writes the skill to dir (or ~/.claude/skills/atlassian-cli when
// dir is empty) and returns the file path.
func installSkill(body, dir string) (string, error) {
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		dir = filepath.Join(home, ".claude", "skills", "atlassian-cli")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "SKILL.md")
	if err := os.WriteFile(path, []byte(skillDocument(body)), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func init() {
	docsCmd.Flags().Bool("skill", false, "Wrap output as a Claude Code SKILL.md")
	docsCmd.Flags().Bool("install", false, "Write the skill to ~/.claude/skills/atlassian-cli/SKILL.md")
	docsCmd.Flags().String("dir", "", "Install directory for --install (default ~/.claude/skills/atlassian-cli)")
	rootCmd.AddCommand(docsCmd)
}
